### ISSUE TITLE
Jonguh shit gaat kapot

### ISSUE THREAD

**Issue by jorenham** [Roccy/HashtagWhatsapp#1]
```
Waiting to pass login screen
Found Steen
Bloxecuting scroll
Traceback (most recent call last):
  File "/home/joren/workspace/HashtagWhatsapp/HashtagWhatsapp/hashtag.py", line 124, in <module>
    main("1/1/2017")
  File "/home/joren/workspace/HashtagWhatsapp/HashtagWhatsapp/hashtag.py", line 121, in main
    hw.scroll_back_to_date(date)
  File "/home/joren/workspace/HashtagWhatsapp/HashtagWhatsapp/hashtag.py", line 68, in scroll_back_to_date
    chat_pane.send_keys(u'\ue00e')
  File "/home/joren/workspace/HashtagWhatsapp/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 347, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT, {'value': keys_to_typing(value)})
  File "/home/joren/workspace/HashtagWhatsapp/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 491, in _execute
    return self._parent.execute(command, params)
  File "/home/joren/workspace/HashtagWhatsapp/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/home/joren/workspace/HashtagWhatsapp/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference is stale. Either the element is no longer attached to the DOM or the page has been refreshed.
```

**Comment by Roccy** [comment]
Jonguh!!!!
